[build]
  command = "npm run build"
  functions = "./functions"

[template]
  branch = "main" # This does not work.

[template.environment]
  NS_URI = "change me to the nightscout url + '/api/v3'"
  NS_TOKEN = "Set your custom Nightscout subject token here"
